apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - $patch: delete
    name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - $patch: delete
    name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: envoy
  type: LoadBalancer

